name: 'Generate API Documentation'
description: 'Generate API documentation using Ollama'
inputs:
  model:
    description: 'Model to use for generating documentation'
    required: true
  temperature:
    description: 'Temperature setting for the model'
    required: false
    default: '0.2'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.model }}
    - ${{ inputs.temperature }}
  volumes:
    - ${{ github.workspace }}/github-pages:/workspace/github-pages
