name: 'Generate API Documentation'
description: 'Generate API documentation using Ollama'
inputs:
  model:
    description: 'Model to use for generating documentation'
    required: true
  temperature:
    description: 'Temperature setting for the model'
    required: false
    default: '0.2'
  globs:
    description: 'File patterns to search for'
    required: false
    default: '*.go'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.model }}
    - ${{ inputs.temperature }}
    - ${{ inputs.globs }}
  env:
    GITHUB_WORKSPACE: ${{ github.workspace }}
