name: Go package

on: [push]

jobs:
  setup-ollama:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Ollama
        id: cache-ollama
        uses: actions/cache@v3
        with:
          path: |
            ollama
            .ollama
          key: ${{ runner.os }}-ollama

      - name: Setup Go
        if: steps.cache-ollama.outputs.cache-hit != 'true'
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build Ollama
        if: steps.cache-ollama.outputs.cache-hit != 'true'
        run: git clone --recursive https://github.com/jmorganca/ollama && cd ollama && go generate ./... && go build -v

      - name: Test the ollama executable
        run: ollama/ollama --help

      - name: Run ollama in the background
        run: ollama/ollama serve &

      - name: Pull the codeup model
        run: ollama/ollama pull codeup

      - name: Upload the ollama executable and codeup model as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ollama-artifacts
          path: |
            ollama/ollama
            .ollama

  run-model:
    needs: setup-ollama
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model:
          - 'codeup:latest'
          #- 'llama2:chat'
          #- 'llama2:text'
          #- 'mistral:7b-text'
          #- 'mistral:7b-instruct'
          #- 'wizardlm-uncensored:13b'
          #- 'codeup:13b-llama2-chat'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the ollama executable artifact and codeup model
        uses: actions/download-artifact@v3
        with:
          name: ollama-artifacts

      - name: Set execute permissions for ollama
        run: chmod +x ollama/ollama

      # Attempt to restore the cache for the .ollama directory
      - name: Cache the .ollama directory
        id: cache-ollama
        uses: actions/cache@v3
        with:
          path: .ollama
          key: ${{ runner.os }}-${{ matrix.model }}-ollama-cache
          restore-keys: |
            ${{ runner.os }}-${{ matrix.model }}-

      - name: Run ollama in the background
        run: ollama/ollama serve &

      # Only pull the model if the cache wasn't restored
      - name: Pull the model
        if: steps.cache-ollama.outputs.cache-hit != 'true'
        run: ollama/ollama pull ${{ matrix.model }}

      - name: Cache the .ollama directory
        uses: actions/cache@v3
        with:
          path: .ollama
          key: ${{ runner.os }}-${{ matrix.model }}-ollama-cache
          restore-keys: |
            ${{ runner.os }}-${{ matrix.model }}-

      - name: Generate a Modelfile
        run: |
          echo "FROM ${{ matrix.model }}" > Modelfile
          echo "PARAMETER temperature 0.1" >> Modelfile
          #echo "EMBED main.go" >> Modelfile
          echo "SYSTEM \"\"\"" >> Modelfile
          #cat main.go >> Modelfile
          cat prompt.txt >> Modelfile
          echo "\"\"\"" >> Modelfile

      - name: Output the Modelfile
        run: cat Modelfile

      - name: Pull and build the model
        run: |
          MODEL_NAME=$(echo "${{ matrix.model }}" | tr ':-' '__')
          ollama/ollama create "${MODEL_NAME}"_custom -f Modelfile

      - name: Generate API documentation
        run: |
          MODEL_NAME=$(echo "${{ matrix.model }}" | tr ':-' '__')
          ollama/ollama run "${MODEL_NAME}"_custom > "${MODEL_NAME}_apidoc.md"

      - name: Output the API documentation
        run: |
          MODEL_NAME=$(echo "${{ matrix.model }}" | tr ':-' '__')
          cat "${MODEL_NAME}_apidoc.md"

      - name: Commit and push the API documentation
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add *_apidoc.md || true
          git commit -m "Add result files from GitHub Actions"
          git log -1 --pretty=%B | grep -q "Update API documentation" || git commit -m "Update API documentation" && git push || true
          git push
