name: Go package

on: [push]

jobs:
  build-ollama:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Ollama Executable
        id: cache-ollama-exec
        uses: actions/cache@v3
        with:
          path: ollama
          key: ollama-exec-${{ runner.os }}-${{ github.run_number // 1000 }} # Refresh every 1000 runs

      - name: Setup Go
        if: steps.cache-ollama-exec.outputs.cache-hit != 'true'
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build Ollama
        if: steps.cache-ollama-exec.outputs.cache-hit != 'true'
        run: |
          git clone --recursive https://github.com/jmorganca/ollama && cd ollama && go generate ./... && go build -v

      - name: Test the ollama executable
        run: ollama/ollama --help

  pull-models:
    needs: build-ollama
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model:
          #- 'codeup:latest'
          - 'llama2:chat'
          # ... other models
    steps:
      - name: Cache Models
        id: cache-models
        uses: actions/cache@v3
        with:
          path: .ollama/
          key: model-${{ matrix.model }}-${{ runner.os }}-${{ github.run_number // 1000 }} # Refresh every 1000 runs

      - name: Pull the model
        if: steps.cache-models.outputs.cache-hit != 'true'
        run: |
          ollama/ollama serve &
          ollama/ollama pull ${{ matrix.model }}

  run-model:
    needs: pull-models
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model:
          #- 'codeup:latest'
          - 'llama2:chat'
          # ... other models
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate a Modelfile
        run: |
          echo "FROM ${{ matrix.model }}" > Modelfile
          echo "PARAMETER temperature 0.1" >> Modelfile
          echo "SYSTEM \"\"\"" >> Modelfile
          cat prompt.txt >> Modelfile
          echo "\"\"\"" >> Modelfile

      - name: Run ollama with the model
        run: |
          MODEL_NAME=$(echo "${{ matrix.model }}_custom" | tr ':-' '__')
          ollama/ollama create "${MODEL_NAME}" -f Modelfile
          ollama/ollama run "${MODEL_NAME}" "$(cat prompt.txt)" > "${MODEL_NAME}.md"

      - name: Commit and push the API documentation
        run: |
          MODEL_NAME=$(echo "${{ matrix.model }}_custom" | tr ':-' '__')
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add "${MODEL_NAME}.md" || true
          git commit -m "Add result files from GitHub Actions"
          git log -1 --pretty=%B | grep -q "Update API documentation" || git commit -m "Update API documentation" && git push || true
