name: Go package

on: [push]

jobs:
  build-ollama:
    strategy:
      matrix:
        model:
          #- 'llama2:chat'
          #- 'codeup:latest'
          - 'codeup:13b-llama2-chat-q2_K'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache ollama executable
        id: cache-ollama-exec
        uses: actions/cache@v2
        with:
          path: ollama/ollama
          key: ollama-exec-${{ runner.os }}-${{ github.run_id }}

      - name: Setup Go
        if: steps.cache-ollama-exec.outputs.cache-hit != 'true'
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Build Ollama
        if: steps.cache-ollama-exec.outputs.cache-hit != 'true'
        run: |
          git clone --recursive https://github.com/jmorganca/ollama && cd ollama && go generate ./... && go build -v

      - name: Test the ollama executable
        run: ollama/ollama --help

      - name: Run ollama in the background
        run: ollama/ollama serve &

      - name: Pull the model
        run: ollama/ollama pull ${{ matrix.model }}

      - name: Generate a Modelfile
        run: |
          echo "FROM ${{ matrix.model }}" > Modelfile
          #echo "PARAMETER temperature 0.1" >> Modelfile

      - name: Run ollama with the model
        run: |
          MODEL_NAME=$(echo "${{ matrix.model }}_custom" | tr ':-' '__')
          ollama/ollama create "${MODEL_NAME}" -f Modelfile
          ollama/ollama run "${MODEL_NAME}" "Write the API documentation for this code. Use Markdown. Here is the code: $(cat main.go)" > "${MODEL_NAME}.md"

      - name: Commit and push the API documentation
        run: |
          MODEL_NAME=$(echo "${{ matrix.model }}_custom" | tr ':-' '__')
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add "${MODEL_NAME}.md" || true
          git commit -m "Add result files from GitHub Actions"
          git log -1 --pretty=%B | grep -q "Update API documentation" || git commit -m "Update API documentation" && git push || true
