name: Action test

on: [push]

jobs:
  'Action test':
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t autodoc-test .

      - name: Run Docker Container
        run: docker run autodoc-test
